<?php

namespace Database\Seeders;

use App\Models\Patient;
use Illuminate\Database\Seeder;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Patient::factory()->create([
            'full_name' => 'João da Silva',
            'cpf' => '12345678900',
            'birth_date' => '1990-01-01',
            'gender' => 'male',
            'mother_name' => 'Maria da Silva',
            'father_name' => 'José da Silva',
            'sus_number' => '134785612378945',
            'medical_record' => 'MR-1234-AB',
            'nationality' => 'Brasileiro',
            'birth_place' => 'São Paulo',
            'state' => 'SP',
            'cep' => '01234000',
            'address' => 'Rua das Flores, 123',
            'number' => '123',
            'complement' => 'Apto 101',
            'neighborhood' => 'Centro',
            'city' => 'São Paulo',
            'state_address' => 'SP',
            'country' => 'Brasil',
            'phone' => '(11) 98765-4321',
        ]);

        Patient::factory()->create([
            'full_name' => 'Maria Oliveira',
            'cpf' => '98765432100',
            'birth_date' => '1985-05-15',
            'gender' => 'female',
            'mother_name' => 'Ana Oliveira',
            'father_name' => 'Carlos Oliveira',
            'sus_number' => '234785612378946',
            'medical_record' => 'MR-5678-CD',
            'nationality' => 'Brasileiro',
            'birth_place' => 'Rio de Janeiro',
            'state' => 'RJ',
            'cep' => '20000000',
            'address' => 'Avenida Brasil, 456',
            'number' => '456',
            'neighborhood' => 'Copacabana',
            'city' => 'Rio de Janeiro',
            'state_address' => 'RJ',
            'country' => 'Brasil',
            'phone' => '(21) 91234-5678',
        ]);

        Patient::factory()->create([
            'full_name' => 'Carlos Souza',
            'cpf' => '11122233344',
            'birth_date' => '1992-07-20',
            'gender' => 'male',
            'mother_name' => 'Lucia Souza',
            'father_name' => 'Paulo Souza',
            'sus_number' => '334785612378947',
            'nationality' => 'Brasileiro',
            'birth_place' => 'Belo Horizonte',
            'state' => 'MG',
            'cep' => '30110000',
            'address' => 'Rua da Bahia, 789',
            'number' => '789',
            'neighborhood' => 'Funcionários',
            'city' => 'Belo Horizonte',
            'state_address' => 'MG',
            'country' => 'Brasil',
            'phone' => '(31) 92345-6789',
        ]);

        Patient::factory()->create([
            'full_name' => 'Ana Santos',
            'cpf' => '55566677788',
            'birth_date' => '1980-03-10',
            'gender' => 'female',
            'mother_name' => 'Marta Santos',
            'father_name' => 'Roberto Santos',
            'sus_number' => '434785612378948',
            'medical_record' => 'MR-9012-EF',
            'nationality' => 'Brasileiro',
            'birth_place' => 'Porto Alegre',
            'state' => 'RS',
            'cep' => '90010000',
            'address' => 'Avenida Farrapos, 321',
            'number' => '321',
            'complement' => 'Sala 5',
            'neighborhood' => 'Centro Histórico',
            'city' => 'Porto Alegre',
            'state_address' => 'RS',
            'country' => 'Brasil',
            'phone' => '(51) 93456-7890',
        ]);

        Patient::factory()->create([
            'full_name' => 'Pedro Costa',
            'cpf' => '99988877766',
            'birth_date' => '1995-12-25',
            'gender' => 'male',
            'mother_name' => 'Fernanda Costa',
            'father_name' => 'Antônio Costa',
            'sus_number' => '534785612378949',
            'nationality' => 'Brasileiro',
            'birth_place' => 'Salvador',
            'state' => 'BA',
            'cep' => '40000000',
            'address' => 'Rua Chile, 654',
            'number' => '654',
            'neighborhood' => 'Comércio',
            'city' => 'Salvador',
            'state_address' => 'BA',
            'country' => 'Brasil',
            'phone' => '(71) 94567-8901',
        ]);

        Patient::factory()->create([
            'full_name' => 'Juliana Almeida',
            'cpf' => '22233344455',
            'birth_date' => '1988-09-09',
            'gender' => 'female',
            'mother_name' => 'Patrícia Almeida',
            'father_name' => 'Marcos Almeida',
            'sus_number' => '634785612378950',
            'medical_record' => 'MR-3456-GH',
            'nationality' => 'Brasileiro',
            'birth_place' => 'Recife',
            'state' => 'PE',
            'cep' => '50000000',
            'address' => 'Rua do Sol, 987',
            'number' => '987',
            'neighborhood' => 'Santo Antônio',
            'city' => 'Recife',
            'state_address' => 'PE',
            'country' => 'Brasil',
            'phone' => '(81) 95678-9012',
        ]);

        Patient::factory()->create([
            'full_name' => 'Lucas Pereira',
            'cpf' => '44455566677',
            'birth_date' => '1993-11-11',
            'gender' => 'male',
            'mother_name' => 'Cristina Pereira',
            'father_name' => 'Ricardo Pereira',
            'sus_number' => '734785612378951',
            'nationality' => 'Brasileiro',
            'birth_place' => 'Brasília',
            'state' => 'DF',
            'cep' => '70000000',
            'address' => 'Quadra 302, 123',
            'number' => '123',
            'neighborhood' => 'Asa Sul',
            'city' => 'Brasília',
            'state_address' => 'DF',
            'country' => 'Brasil',
            'phone' => '(61) 96789-0123',
        ]);

        Patient::factory()->create([
            'full_name' => 'Fernanda Lima',
            'cpf' => '77788899900',
            'birth_date' => '1982-06-06',
            'gender' => 'female',
            'mother_name' => 'Isabel Lima',
            'father_name' => 'Gustavo Lima',
            'sus_number' => '834785612378952',
            'nationality' => 'Brasileiro',
            'birth_place' => 'Fortaleza',
            'state' => 'CE',
            'cep' => '60000000',
            'address' => 'Avenida Beira Mar, 456',
            'number' => '456',
            'complement' => 'Bloco B',
            'neighborhood' => 'Meireles',
            'city' => 'Fortaleza',
            'state_address' => 'CE',
            'country' => 'Brasil',
            'phone' => '(85) 97890-1234',
        ]);

        Patient::factory()->create([
            'full_name' => 'Rafael Gonçalves',
            'cpf' => '33344455566',
            'birth_date' => '1998-04-04',
            'gender' => 'male',
            'mother_name' => 'Sandra Gonçalves',
            'father_name' => 'Eduardo Gonçalves',
            'sus_number' => '934785612378953',
            'medical_record' => 'MR-7890-IJ',
            'nationality' => 'Brasileiro',
            'birth_place' => 'Curitiba',
            'state' => 'PR',
            'cep' => '80000000',
            'address' => 'Rua XV de Novembro, 789',
            'number' => '789',
            'neighborhood' => 'Centro',
            'city' => 'Curitiba',
            'state_address' => 'PR',
            'country' => 'Brasil',
            'phone' => '(41) 98901-2345',
        ]);

        Patient::factory()->create([
            'full_name' => 'Patrícia Rocha',
            'cpf' => '66677788899',
            'birth_date' => '1987-08-08',
            'gender' => 'female',
            'mother_name' => 'Alice Rocha',
            'father_name' => 'Daniel Rocha',
            'sus_number' => '1034785612378954',
            'nationality' => 'Brasileiro',
            'birth_place' => 'Manaus',
            'state' => 'AM',
            'cep' => '69000000',
            'address' => 'Avenida Eduardo Ribeiro, 321',
            'number' => '321',
            'neighborhood' => 'Centro',
            'city' => 'Manaus',
            'state_address' => 'AM',
            'country' => 'Brasil',
            'phone' => '(92) 99012-3456',
        ]);
    }
}
